import { useState, useEffect, useCallback } from 'react';

// Hook to load pre-fetched contract data
export function useContractData() {
  const [contractData, setContractData] = useState(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState(null);
  const [lastFetch, setLastFetch] = useState(null);

  // Load contract data from the pre-generated JSON file
  const loadContractData = useCallback(async () => {
    try {
      setIsLoading(true);
      setError(null);
      
      console.log('📖 Loading contract data from cache...');
      
      // Load from the public JSON file (generated by the script)
      const response = await fetch('/contract-data.json', {
        cache: 'no-cache', // Ensure we get the latest version
        headers: {
          'Cache-Control': 'no-cache',
        },
      });
      
      if (!response.ok) {
        throw new Error(`Failed to load contract data: ${response.status} ${response.statusText}`);
      }
      
      const data = await response.json();
      
      // Validate the data structure
      if (!data.tokens || !Array.isArray(data.tokens)) {
        throw new Error('Invalid contract data format');
      }
      
      setContractData(data);
      setLastFetch(new Date(data.metadata.fetchedAt));
      
      console.log(`✅ Contract data loaded: ${data.tokens.length} tokens`);
      console.log(`📅 Data fetched at: ${data.metadata.fetchedAt}`);
      
    } catch (err) {
      console.error('❌ Error loading contract data:', err);
      setError(err.message);
    } finally {
      setIsLoading(false);
    }
  }, []);

  // Load data on component mount
  useEffect(() => {
    loadContractData();
  }, [loadContractData]);

  // Helper functions to work with the data
  const getToken = useCallback((tokenId) => {
    return contractData?.tokens?.find(token => token.id === parseInt(tokenId));
  }, [contractData]);

  const getTokens = useCallback(() => {
    return contractData?.tokens || [];
  }, [contractData]);

  const getActiveTokens = useCallback(() => {
    return contractData?.tokens?.filter(token => token.isAvailable) || [];
  }, [contractData]);

  const getWhitelistTokens = useCallback(() => {
    return contractData?.tokens?.filter(token => token.isWhitelistActive) || [];
  }, [contractData]);

  const getSummary = useCallback(() => {
    return contractData?.summary || {
      totalTokens: 0,
      totalMinted: 0,
      totalAvailable: 0,
      activeTokens: 0,
      whitelistActiveTokens: 0
    };
  }, [contractData]);

  const getMetadata = useCallback(() => {
    return contractData?.metadata || null;
  }, [contractData]);

  // Check if data is stale (older than 30 minutes)
  const isDataStale = useCallback(() => {
    if (!contractData?.metadata?.fetchedTimestamp) return true;
    
    const now = Date.now();
    const fetchTime = contractData.metadata.fetchedTimestamp;
    const thirtyMinutes = 30 * 60 * 1000;
    
    return (now - fetchTime) > thirtyMinutes;
  }, [contractData]);

  // Get data age in a human-readable format
  const getDataAge = useCallback(() => {
    if (!contractData?.metadata?.fetchedTimestamp) return null;
    
    const now = Date.now();
    const fetchTime = contractData.metadata.fetchedTimestamp;
    const diffMs = now - fetchTime;
    
    const minutes = Math.floor(diffMs / (1000 * 60));
    const hours = Math.floor(diffMs / (1000 * 60 * 60));
    const days = Math.floor(diffMs / (1000 * 60 * 60 * 24));
    
    if (days > 0) return `${days} day${days > 1 ? 's' : ''} ago`;
    if (hours > 0) return `${hours} hour${hours > 1 ? 's' : ''} ago`;
    if (minutes > 0) return `${minutes} minute${minutes > 1 ? 's' : ''} ago`;
    return 'Just now';
  }, [contractData]);

  return {
    // Data
    contractData,
    tokens: getTokens(),
    
    // State
    isLoading,
    error,
    lastFetch,
    
    // Helper functions
    getToken,
    getTokens,
    getActiveTokens,
    getWhitelistTokens,
    getSummary,
    getMetadata,
    
    // Utilities
    isDataStale,
    getDataAge,
    refresh: loadContractData,
  };
} 